name: demo_firebase
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_messaging: ^15.2.4
  google_sign_in: ^5.0.7
  flutter_native_splash: ^2.4.4
  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.4.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  sprintf: ^7.0.0
  crypto: ^3.0.6
  http: ^1.3.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.14.3
  # Map
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  latlong2: ^0.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo2.png
  android_12:
    image: assets/logo2.png
    color: "#FFFFFF"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
